### PR TITLE
Add all platform links on main page

### PR DESCRIPTION
**Pull request by theSage21**
You can preview the site using the netlify jobs in CI.

@sakshamtaneja21 @Pratul1997 @Shivank98 these are the only social links we have right? Are there any that I've missed?

- Updated README files with new instructions
- Update issue and PR templates for adding new events
- SVG logo for pyjaipur
- Site background is a little lighter to contrast less with the logo
- Add social platforms on main page
image

### CODE REVIEW

**Comment by sakshamtaneja21** [comment]
Instagram

**Comment by theSage21** [comment]
Who has access to that?

**Comment by Pratul1997** [comment]
@theSage21 Facebook

**Comment by theSage21** [comment]
Can you comment the links for these? I'm not aware of them.

We also need to figure out who has access for these accounts.

**Comment by theSage21** [comment]
Unless these are connected using the PyJaipur email address. Then it's ok.

**Comment by Pratul1997** [comment]
https://www.facebook.com/groups/PyJaipur/
https://www.facebook.com/PyJaipur/

@theSage21 

@kirtibajaj has access to the accounts, I guess for Instagram as well.

**Comment by Pratul1997** [comment]
@theSage21 
Instagram is with pyjaipur email id.

**Comment by sakshamtaneja21** [comment]
Yeah for Instagram kirti di has access and  for Facebook also I think

**Comment by Shivank98** [comment]
we can leave Facebook no need to put things there. rarely anyone uses.
Instagram is good to have good pics but currently no one is there to manage it.
Mailing list Icon should be there ( I have took responsibility of that)

**Comment by theSage21** [comment]
Ah yes. I'll add the mailing list icon.

**Comment by theSage21** [comment]
We'll skip facebook and instagram for now since there's nobody to maintain them.

**Comment by theSage21** [comment]
@Shivank98 mailman link is added. I used a gmail icon since it's very recognizable as an email service.

**Comment by theSage21** [comment]
Can we merge this or is anything else pending?

**Comment by Shivank98** [comment]
I haven't checked the code yet as I am traveling. you can merge if you want.

**Comment by theSage21** [comment]
No no.

Reach home, see the choice and then approve the pr.

**Pull request merged**
